Fix conflict with unistd.h
Rename pause() to pause_play().

This commit fixes the following build error:

../audio/out/ao_pulse.c:539:13: error: conflicting types for ‘pause’; have ‘void(struct ao *)’
  539 | static void pause(struct ao *ao)
      |             ^~~~~
In file included from /usr/include/bits/sigstksz.h:24,
                 from /usr/include/signal.h:328,
                 from /usr/include/sys/param.h:28,
                 from /usr/include/pulse/sample.h:26,
                 from /usr/include/pulse/def.h:28,
                 from /usr/include/pulse/direction.h:23,
                 from /usr/include/pulse/pulseaudio.h:24,
                 from ../audio/out/ao_pulse.c:28:
/usr/include/unistd.h:489:12: note: previous declaration of ‘pause’ with type ‘int(void)’
  489 | extern int pause (void);
      |            ^~~~~